<?php
    //HTTP CODES
    $HTTP_OK = 200;
    $HTTP_NO_CONTENT = 204;
    $HTTP_CREATED = 201;
    $HTTP_SERVER_UNAVAILABLE = 503;
    $HTTP_BAD_REQUEST = 400;

    //MESSAGES-TYPE
    $ERROR_MESSAGE = 'ERR-MSG';
    $INFO_MESSAGE = 'INFO-MSG';